git:
  depth: 5

jobs:
  include:
    - stage: "Build and Test Java"
      language: "java"
      jdk: "oraclejdk11"
      before_script:
        - "cd sample-application-backend"
      script:
        - "mvn clean verify" 
        - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent" 
        - "mvn sonar:sonar -Dsonar.projectKey=$SONARCLOUD_PROJECTKEY"
    - stage: "Build and Test Nodejs"
      language: "node_js"
      node_js: "12.20"
      before_install:
        - "cd sample-application-frontend"
      install:
        - "npm install"
      script:
        - "npm run test"
    - stage: "Publish"
      script:
        - "cd sample-application-backend"
        - "docker build -t $DOCKERHUB_LOGIN/simpleapp-back:latest ."
        - "docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD"
        - "docker push $DOCKERHUB_LOGIN/simpleapp-back:latest"
    - stage: "Publish"
      script:
        - "cd sample-application-frontend"
        - "docker build -t $DOCKERHUB_LOGIN/simpleapp-front:latest ."
        - "docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD"
        - "docker push $DOCKERHUB_LOGIN/simpleapp-front:latest"
    - stage: "Deploy"
      before_script:
        - "openssl aes-256-cbc -K $encrypted_c02febb1adb2_key -iv $encrypted_c02febb1adb2_iv -in deploy_key.enc -out deploy_key -d"
        - "chmod 0400 deploy_key"
      script:
        - "ssh -i deploy_key -o StrictHostKeyChecking=no centos@yoann.drevet.takima.cloud docker stop backend"
        - "ssh -i deploy_key -o StrictHostKeyChecking=no centos@yoann.drevet.takima.cloud docker remove backend"
        - "ssh -i deploy_key -o StrictHostKeyChecking=no centos@yoann.drevet.takima.cloud docker run --net myapp-net --name backend -d -p 80:80 ydrevet/simpleapp-back"
      on:
        branch: production
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

addons:
    sonarcloud:
        organization: "ydrevet"
        token: "$SONARCLOUD_TOKEN"



