---
# Launch front
- name: Launch frontend
  docker_container:
    name: frontend
    state: started
    image: ydrevet/simpleapp-front:latest
    ports:
      - "80:80"
    purge_networks: yes
    networks:
      - name: myapp-net


